export const desk = {
  interviewRoom: "חדר ראיונות",
  interviewRoomFull: "חדר ראיונות · שולחן העורכים",
  liveInterview: "ראיון חי",
  reporter: "כתב",
  reporterName: "כתב העיתון",
  reporterSubtitle: "שואל שאלות המשך ומנסח ידיעה לאישור",
  angleChosen: "זווית נבחרה",
  factsLocked: (n: number) => (n === 1 ? "עובדה נעולה אחת" : `${n} עובדות נעולות`),
  close: "סגירה",
  closeAndReturn: "סגירה וחזרה לעיתון",
  composerLabel: "מה קרה?",
  composerPlaceholder: "פרטו את הידיעה כפי שתרצו לראותה בעיתון",
  send: "שליחה",
  writeDraft: "נסחו טיוטה",
  consentNote: "שום ידיעה לא תפורסם ללא אישור שלך",
  writingDraft: "הכתב מנסח טיוטה…",
  suggestedOpeners: "התחלות מוצעות",
  noDraftYet: "אין טיוטה עדיין — כשתרצו ידיעה, בקשו מהכתב לנסח",
  interviewClosed: "הכתב סיים לשאול — הטיוטה מוכנה לאישור",
  interviewEnded: "הראיון נסגר",
  discard: "בטלו את הראיון",
  startOver: "התחילו מחדש",
  retry: "נסו שוב",

  draft: "טיוטה",
  editing: "בעריכה",
  angle: "זווית",
  headline: "כותרת",
  standfirst: "כותרת משנה",
  body: "גוף",
  deskChecks: "בדיקות שולחן העורכים",
  section: "מדור",
  publish: "פרסמו במהדורה",
  editManually: "עריכה ידנית",
  saveDraft: "שמרו כטיוטה",
  publishNote: "פרסום יעלה את הידיעה לעמוד הראשי כמבזק וכידיעה מלאה",
  showDraft: "הצגת הטיוטה",
  hideDraft: "חזרה לשיחה",

  emptyFirstTitle: "ספרו מה קרה",
  emptyFirstBody: "הכתב ישאל שאלות המשך.",

  waitingTitle: "הכתב ממתין לך",
  continueDraft: "המשך לטיוטה",
  openInterviewRoom: "פתחו את חדר הראיונות",
  openInterview: "ראיון פתוח",

  emptyEditionKicker: "שולחן העורכים ממתין לראיון הראשון",
  emptyEditionTitle: "המהדורה הראשונה שלך עוד לא נכתבה",
  emptyEditionBody:
    "אין כאן ידיעות כי עוד לא סיפרת כלום. ספר לכתב מה קרה השבוע — הוא ישאל, יבחר זווית, ויחזיר טיוטה לאישור שלך.",
  emptyEditionDraftTitle: "יש טיוטה בעריכה",
  emptyEditionDraftBody: (title: string) =>
    `«${title}» מחכה בחדר הראיונות. המשיכו משם במקום להתחיל ראיון חדש.`,
  startFirstInterview: "התחילו ראיון ראשון",
  fillKarteset: "מלאו רקע בכרטסת",
  quotaTitle: "הגעתם לשתי ידיעות להיום",
  quotaBody: "מחר הכתב מחכה שוב.",
  archiveEmpty: "עוד אין ראיונות בארכיון",
  archivedInterview: "ראיון מהארכיון",
  archive: "ארכיון",
  backToEdition: "חזרה למהדורה",
  noFlashes: "לא נמצאו מבזקים כרגע",
  tomorrowTitle: "מה יכול להיות כאן מחר",
  tomorrowCards: [
    { kicker: "ראשי", text: "כותרת ראשית מהשבוע שלך" },
    { kicker: "ראשי", text: "ידיעה על מישהו קרוב" },
    { kicker: "מבזקים", text: "מבזק קטן מהיום" },
  ],

  moreIn: (section: string) => `עוד ב${section}`,
  moreInEdition: "עוד במהדורה",

  articleType: "סוג",
  articleTone: "טון",
  articleFormAuto: "אוטומטי",
  articleTypes: {
    news: "חדשות",
    profile: "פרופיל",
    feature: "מגזין",
    interview: "ראיון",
    column: "טור",
  },
  articleTones: {
    factual: "ענייני",
    magazine: "מגזיני",
    witty: "שנון",
    dramatic: "דרמטי",
    intimate: "אינטימי",
  },
  articleTypeHints: {
    news: "חדשותית — מה קרה, למי, מתי, איפה ולמה",
    profile: "פרופיל — אדם דרך אישיות, הרגלים, חיים",
    feature: "כתבת מגזין — סיפור רחב סביב נושא / תופעה / זווית אנושית",
    interview: "ראיון — בנוי בעיקר סביב דברי המרואיין",
    column: "טור / פרשנות — עמדה או נקודת מבט של הכותב",
  },
  articleToneHints: {
    factual: "עיתונאי ענייני — נקי, עובדתי, ישיר",
    magazine: "מגזיני סיפורי — תיאורי, זורם, עם סצנות",
    witty: "קליל ושנון — הומור עדין, ניסוחים חדים",
    dramatic: "דרמטי — מדגיש מתח, קונפליקט ומשמעות",
    intimate: "אישי ואינטימי — חם, קרוב לדמות",
  },
} as const;
