export const desk = {
  interviewRoom: "חדר ראיונות",
  interviewRoomFull: "חדר ראיונות · שולחן העורכים",
  liveInterview: "ראיון חי",
  reporter: "כתב",
  reporterName: "כתב העיתון",
  reporterSubtitle: "שואל שאלות המשך ומנסח ידיעה לאישור",
  angleChosen: "זווית נבחרה",
  factsLocked: (n: number) => `${n} עובדות נעולות`,
  close: "סגירה",
  closeAndReturn: "סגירה וחזרה לעיתון",
  composerLabel: "מה קרה?",
  composerPlaceholder: "פרטו את הידיעה כפי שתרצו לראותה בעיתון",
  send: "שליחה",
  writeDraft: "נסחו טיוטה",
  consentNote: "שום ידיעה לא תפורסם ללא אישור שלך",
  writingDraft: "הכתב מנסח טיוטה…",
  suggestedOpeners: "התחלות מוצעות",
  noDraftYet: "אין טיוטה עדיין — כשתרצו ידיעה, בקשו מהכתב לנסח",
  interviewClosed: "הכתב סיים לשאול — הטיוטה מוכנה לאישור",

  draft: "טיוטה",
  editing: "בעריכה",
  angle: "זווית",
  headline: "כותרת",
  standfirst: "כותרת משנה",
  body: "גוף",
  deskChecks: "בדיקות שולחן העורכים",
  section: "מדור",
  publish: "פרסמו במהדורה",
  editManually: "עריכה ידנית",
  saveDraft: "שמרו כטיוטה",
  publishNote: "פרסום יעלה את הידיעה לעמוד הראשי כמבזק וכידיעה מלאה",
  showDraft: "הצגת הטיוטה",
  hideDraft: "חזרה לשיחה",

  emptyFirstTitle: "הכתב מחכה לראיון הראשון",
  emptyFirstBody:
    "מה קרה? ספרו בקצרה. הכתב ישאל שאלות המשך, יבחר זווית — וכשתרצו, ינסח ידיעה לאישור.",

  waitingTitle: "הכתב ממתין לך",
  continueDraft: "המשך לטיוטה",
  openInterviewRoom: "פתחו את חדר הראיונות",

  emptyEditionKicker: "שולחן העורכים ממתין לראיון הראשון",
  emptyEditionTitle: "המהדורה הראשונה שלך עוד לא נכתבה",
  emptyEditionBody:
    "אין כאן ידיעות כי עוד לא סיפרת כלום. ספר לכתב מה קרה השבוע — הוא ישאל, יבחר זווית, ויחזיר טיוטה לאישור שלך.",
  startFirstInterview: "התחילו ראיון ראשון",
  fillKarteset: "מלאו רקע בכרטסת",
  noFlashes: "לא נמצאו מבזקים כרגע",
  tomorrowTitle: "מה יכול להיות כאן מחר",
  tomorrowCards: [
    { section: "עבודה", text: "כותרת ראשית מהשבוע שלך" },
    { section: "משפחה", text: "ידיעה על מישהו קרוב" },
    { section: "רגעים", text: "מבזק קטן מהיום" },
  ],

  moreIn: (section: string) => `עוד ב${section}`,
  moreInEdition: "עוד במהדורה",
} as const;
